version: "2.2"
services:
  frontend:
    # uncomment for local dev
    build: ./
    restart: always
    image: gitlab.zbmed.de:5050/km/semlookp/semlookp-sampleapp/frontend:${VERSION}
    ports:
      - ${PORT}:8080
