name: Continuous Integration

on:
  pull_request: { branches: ["main"] }
  push:
    branches: ["main"]
    tags: ["*"]
env:
  GIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    name: "Build Image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: generate-image-tag
        name: Generate Image Tag
        env:
          ref_name: "${{ github.ref_name }}"
          head_ref: "${{ github.head_ref }}"
        run: |
          head_ref="${head_ref/\//-}"
          ref_name="${head_ref:-${ref_name/main/latest}}"
          echo "::set-output name=imageTag::${ref_name#v}"
      - name: Configure npm to use registry for @ts4nfdi scope
        run: echo "@ts4nfdi:registry=https://npm.pkg.github.com" >> .npmrc
      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.SEMLOOKP_WIDGETS_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com/"
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.SEMLOOKP_WIDGETS_TOKEN }}
        working-directory: .
      - run: npm run build
        env:
          CI: false
        working-directory: .
      - name: Build and Push Frontend
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.generate-image-tag.outputs.imageTag }}
            ghcr.io/${{ github.repository }}:${{ github.event.pull_request.head.sha || github.sha }}