# berd
name: Deployment to production
concurrency: production
on:
  workflow_dispatch:
    inputs:
      image_name:
        description: "Name of the Docker image"
        required: true
        type: string
env:
  KUBECONFIG: .kube/config
  KUBECONFIG_FILE: ${{ secrets.KUBECONFIG_PROD }}
  IMAGE_NAME: ${{ github.event.inputs.image_name }}
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir -p .kube
          echo "${{ env.KUBECONFIG_FILE }}" > $KUBECONFIG
      - uses: stefanprodan/kube-tools@v1
        with:
          helmv3: 3.12.0
          command: |
            helmv3 repo add semlookp-deployment https://zbmed.github.io/semlookp-deployment/
            helmv3 repo update
            helmv3 upgrade zbmed-ts-berd \
            --install \
            --namespace='zbmed-ts-berd' \
            --set-json='images.ui="${{ env.IMAGE_NAME }}"' \
            --set-json='ingress.dns="ts.berd-nfdi.de"'  \
            --set-json='ingress.path="/"'  \
            --set-json='ingress.enableSSL="true"'  \
            --set-json='ingress.certIssuer="letsencrypt-prod"'  \
            semlookp-deployment/semlookp-ui
